package com.ab.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;


@Entity
@Table(name="exchange")

public class Exchange {
	
	private int exchnageId;
	private double feeLadder;

	
	@OneToMany(targetEntity=OrderBook.class,
			fetch=FetchType.EAGER,
			mappedBy = "exchange",
			cascade = CascadeType.ALL)
	private List<OrderBook> orderBooks = new ArrayList<>();
	

	public Exchange(int exchnageId, double feeLadder, List<OrderBook> orderBooks) {
		super();
		this.exchnageId = exchnageId;
		this.feeLadder = feeLadder;
		this.orderBooks = orderBooks;
	}
	
	public Exchange() {}
	
	
	public int getExchnageId() {
		return exchnageId;
	}

	public void setExchnageId(int exchnageId) {
		this.exchnageId = exchnageId;
	}

	public double getFeeLadder() {
		return feeLadder;
	}

	public void setFeeLadder(double feeLadder) {
		this.feeLadder = feeLadder;
	}

	public List<OrderBook> getOrderBooks() {
		return orderBooks;
	}

	public void setOrderBooks(List<OrderBook> orderBooks) {
		this.orderBooks = orderBooks;
	}

	private double currentDayTotalTradedValue() {
		//Revenue generated by that exchange per day
		//sum of total price of completed orders on that exchange
		return 0.0;
	}

	@Override
	public String toString() {
		return "Exchange [exchnageId=" + exchnageId + ", feeLadder=" + feeLadder + ", orderBooks=" + orderBooks + "]";
	}
	
	
	

}
