package com.ab.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;


@Entity
@Table(name="exchange")

public class Exchange {
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
	private int exchangeId;
	private double feeLadder;

	
	@OneToMany(targetEntity=OrderBook.class,
			fetch=FetchType.EAGER,
			mappedBy = "exchange",
			cascade = CascadeType.ALL)
	private List<OrderBook> orderBooks = new ArrayList<>();
	
	
	//ManyToMany
	@ManyToMany
	private List<Stock> stocks = new ArrayList<>();
	
	
	//ManyToMany
		@ManyToMany
		private List<User> users = new ArrayList<>();
	

	public Exchange(int exchangeId, double feeLadder, List<OrderBook> orderBooks) {
		super();
		this.exchangeId = exchangeId;
		this.feeLadder = feeLadder;
		this.orderBooks = orderBooks;
	}
	
	public Exchange() {}
	
	
	public int getExchangeId() {
		return exchangeId;
	}

	public void setExchangeId(int exchangeId) {
		this.exchangeId = exchangeId;
	}

	public double getFeeLadder() {
		return feeLadder;
	}

	public void setFeeLadder(double feeLadder) {
		this.feeLadder = feeLadder;
	}

	public List<OrderBook> getOrderBooks() {
		return orderBooks;
	}

	public void setOrderBooks(List<OrderBook> orderBooks) {
		this.orderBooks = orderBooks;
	}

	private double currentDayTotalTradedValue() {
		//Revenue generated by that exchange per day
		//sum of total price of completed orders on that exchange
		return 0.0;
	}

	@Override
	public String toString() {
		return "Exchange [exchangeId=" + exchangeId + ", feeLadder=" + feeLadder + ", orderBooks=" + orderBooks + "]";
	}
	
	
	

}
